#!/usr/bin/env python3
"""Builds the in-game menu's text table (bbport_text.cpp includes it) from the locale files
next to this script: one flat JSON object per language ({"key": "text"}), en.json the reference.
  gen_text.py OUT.inc            write the table
  gen_text.py --check            every locale has en.json's keys and printf placeholders"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLACEHOLDER = re.compile(r"%[-+ #0]*\d*(?:\.\d+)?[sdif%]")


def locales():
    return {p.stem: json.loads(p.read_text()) for p in sorted(HERE.glob("*.json"))}


def check(all_locales):
    ref = all_locales["en"]
    ok = True
    for name, texts in all_locales.items():
        missing = sorted(set(ref) - set(texts))
        extra = sorted(set(texts) - set(ref))
        wrong = sorted(k for k in ref if k in texts and PLACEHOLDER.findall(ref[k]) != PLACEHOLDER.findall(texts[k]))
        status = "ok" if not (missing or extra or wrong) else "PROBLEMS"
        print(f"{name + '.json':12} {len(texts):3} keys  {status}")
        for label, items in (("missing", missing), ("extra", extra), ("placeholders differ", wrong)):
            if items:
                ok = False
                print(f"   {label}: {', '.join(items)}")
    return ok


def c_string(text):
    return '"' + text.encode("utf-8").decode("utf-8").replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main():
    all_locales = locales()
    if sys.argv[1:] == ["--check"]:
        sys.exit(0 if check(all_locales) else 1)
    lines = ["// Generated by gpu/shim/locales/gen_text.py from gpu/shim/locales/*.json. Do not edit.",
             "static constexpr TextEntry kTexts[] = {"]
    for name, texts in all_locales.items():
        for key, text in sorted(texts.items()):
            lines.append(f"    {{{c_string(name)}, {c_string(key)}, {c_string(text)}}},")
    lines.append("};")
    Path(sys.argv[1]).write_text("\n".join(lines) + "\n", encoding="utf-8")


main()
